	{"name" : "Elephant",
	 "color" : "grey",
	 "weight" : 7000,
	 "has_tusks": true,
	 "data" : ["mammal", "herbivore", "live in groups"],
	 "found_in" : [ "sub-Saharan Africa", "South Asia", "Southeast Asia" ] },
	{"name" : "Elk",
	 "color" : "brown",
	 "weight" : 395,
	 "min_weight_male": 320,
	 "max_weight_male": 475,
	 "min_weight_female": 275,
	 "max_weight_female": 375,
	 "has_antlers": true,
	 "data" : [ "mammal", "deer family", "herbivore" ],
	 "found_in" : ["Canada", "Alaska", "New England", "Scandinavia", "Latvia", "Estonia", "Russia" ] },
	{"name" : "Fox",
	 "color" : "orange",
	 "weight" : 6,
	 "suborder": "Caniformia",
	 "class": "Mammalia",
	 "order": "Carnivora",
	 "family": "Canidae",	 
	 "data" : [ "mammal", "omnivore"] },
	{"name" : "Wolf",
	 "class": "Mammalia",
	 "order": "Carnivora",
	 "suborder": "Caniformia",
	 "color" : "grey",
	 "weight" : 44,
	 "min_weight_male": 43,
	 "max_weight_male": 45,
	 "min_weight_female": 36,
	 "max_weight_female": 38.5,
	 "found_in" : [ "Eurasia", "North America" ],
	 "data" : ["mammal", "carnivore", "canid", "live in groups" ] },
	{"name" : "Bear",
	 "color" : "brown",
	 "weight" : 505,
	 "found_in": ["North America", "South America", "Europe", "Asia"],
	 "class": "Mammalia",
	 "order": "Carnivora",
	 "suborder": "Caniformia",
	 "family": "Ursidae",
	 "data" : ["mammal", "carnivore", "nonretractile claws", "rounded ears", "can stand on its rear legs" ] },
	{"name" : "Hyena",
	 "family": "Hyaenidae",
	 "suborder": "Feliformia",
	 "order": "Carnivora",
	 "color": "brown",
	 "weight" : 47,
	 "min_weight_male": 40.5,
	 "max_weight_male": 55,
	 "min_weight_female": 44.5,
	 "max_weight_female": 63.9,
	 "spotted": true,
	 "data" : [ "mammal", "carnivore", "live in groups" ] },
	{"name" : "Orangutan",
	 "alternative_name": "Orangutang",
	 "color" : "orange",
	 "weight" : 75,
	 "data" : ["herbivore","opposable thumbs", "opposable big toe", "eat fruits", "primate", "ape"] },
	{"name" : "Reindeer",
	 "class": "Mammalia",
	 "color" : "grey",
	 "weight" : 200,
	 "alternative_name": "caribou",
	 "has_antlers": true,
	 "found_in": [ "northern Europe", "Siberia", "North America" ],
	 "data" : [ "mammal", "deer family", "herbivore", "live in groups" ] },
	{"name" : "Gorilla",
	 "color" : "black",
	 "weight" : 155,
	 "data" : [ "primate", "ape", "herbivore", "can stand on its rear legs", "live in groups" ] },
	{"name" : "Chimpanzee",
	 "color" : "black",
	 "weight" : 70,
	 "data" : [ "primate", "ape", "omnivore"] },
	{"name" : "Marten",
	 "order": "Carnivora",
	 "suborder": "Caniformia",
	 "family": "Mustelidae",
	 "color" : "brown",
	 "weight" : 1.5,
	 "data" : [ "solitary animal" ] },
	{"name" : "Mongoose",
	 "color" : "brown",
	 "weight" : 1.7,
	 "family": "Herpestidae",
	 "suborder": "Feliformia",
	 "order": "Carnivora",
	 "data" : [ "carnivore", "eat venomous snakes" ] },
	{"name" : "Meerkat",
	 "found_in" : ["Botswana", "Namibia", "Angola", "South Africa" ],
	 "color" : "yellow", 
	 "family": "Herpestidae",
	 "suborder": "Feliformia",
	 "order": "Carnivora",
	 "weight" : 1,
	 "data" : [ "can stand on its rear legs", "live in groups" ] },
	{"name" : "Lion",
	 "color" : "yellow",
	 "weight" : 200,
	 "class": "Mammalia",
	 "order": "Carnivora",
	 "family": "Felidae",
	 "subfamily": "Pantherinae",
	 "suborder": "Feliformia",
	 "data" : [ "live in groups", "carnivore", "smaller than tigers", "protractible claws" ] },
	{"name" : "Raccoon",
	 "color" : "gray",
	 "weight" : 6,
	 "suborder": "Caniformia",
	 "class": "Mammalia",
	 "order": "Carnivora",
	 "family": "Procyonidae",
	 "data" : [ "omnivore", "nocturnal", "plantigrade locomotion", "can stand on its rear legs" ] },
	{"name" : "Black panther",
	 "class": "Mammalia",
	 "order": "Carnivora",
	 "family": "Felidae",
	 "subfamily": "Pantherinae",
	 "suborder": "Feliformia",
	 "color" : "black",
	 "weight" : 60,
	 "data" : [ "are leopards in Asia and Africa", "are black jaguars in the Americas", "big cat" ] }
